units:
  - path: /autoware/sensing/sample_mobile_robot_sensor
    type: and
    list:
      - {type: link, link: /autoware/sensing/lidar/top/connection }
      - {type: link, link: /autoware/sensing/lidar/front/connection }
      - {type: link, link: /autoware/sensing/imu/connection }

# top lidar
  - path: /autoware/sensing/lidar/top/connection
    type: diag
    node: topic_state_monitor_lidar_top
    name: lidar_top_topic_status
    timeout: 1.0
# front lidar
  - path: /autoware/sensing/lidar/front/connection
    type: diag
    node: topic_state_monitor_lidar_front
    name: lidar_front_topic_status
    timeout: 1.0
# IMU
  - path: /autoware/sensing/imu/connection
    type: diag
    node: topic_state_monitor_imu
    name: imu_topic_status
    timeout: 1.0
