/**:
  ros__parameters:
    sensing:
      type: diagnostic_aggregator/AnalyzerGroup
      path: sensing
      analyzers:
        lidar:
          type: diagnostic_aggregator/AnalyzerGroup
          path: lidar
          analyzers:
            hesai:
              type: diagnostic_aggregator/AnalyzerGroup
              path: hesai
              analyzers:
                health_monitoring:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: health_monitoring
                  analyzers:
                    status:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: status
                      contains: [": hesai_status"]
                      timeout: 3.0

                    ptp:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: ptp
                      contains: [": hesai_ptp"]
                      timeout: 3.0

                    temperature:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: temperature
                      contains: [": hesai_temperature"]
                      timeout: 3.0

                    rpm:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: rpm
                      contains: [": hesai_rpm"]
                      timeout: 3.0

                    voltage:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: voltage
                      contains: [": hesai_voltage"]
                      timeout: 3.0

        imu:
          type: diagnostic_aggregator/AnalyzerGroup
          path: imu
          analyzers:
            node_alive_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: node_alive_monitoring
              analyzers:
                topic_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: topic_status
                  contains: [": imu_topic_status"]
                  timeout: 1.0
